### ISSUE TITLE
need a telegram bot

### ISSUE THREAD

**Issue by rsoorajs** [developeranaz/URL-TO-MEGA-HEROKU#1]
right now we have to keep opened this window to finish the process, enable that as a background process and can you also make a telegram bot too ?

**Comment by developeranaz** [comment]
@telegrambotdev thanks for sharing your ideas.

You don't need to keep that window open the process will be done in background and send to your mega perfectly.

Currently i mm trying to make multi upload of this version.
But i hate making UI, logos of every webapp , i know this is the worst webapp in Github.

If you are looking for a telegram bot you should need to met a better developer.😂

**Comment by rsoorajs** [comment]
haha thanks for your response ☺️
