### ISSUE TITLE
Cannot bind to $PORT

### ISSUE THREAD

**Issue by Amanse** [developeranaz/URL-TO-MEGA-HEROKU#2]
Heroku is killing the application since it's not binding to $PORT

**Comment by developeranaz** [comment]
no one uses this uploder including me☹️

**Comment by Amanse** [comment]
oh hehe, no problem 😂

**Comment by developeranaz** [comment]
Use URL-Magnet-Cloud-Uploader-Heroku https://github.com/developeranaz/URL-Magnet-Cloud-Uploader-Heroku 
This could upload any direct / magnet link to any rclone cloud (including mega)

**Comment by developeranaz** [comment]
> Use URL-Magnet-Cloud-Uploader-Heroku https://github.com/developeranaz/URL-Magnet-Cloud-Uploader-Heroku This could upload any direct / magnet link to any rclone cloud (including mega)

but personal use only

**Comment by Amanse** [comment]
wow, thank you so much!

**Comment by Amanse** [comment]
this is amazing, rclone rocks!

**Comment by developeranaz** [comment]
i will try to fix this 🤣😂.

**Comment by Amanse** [comment]
haha 😂 rclone one is pretty awesome doe!! i think just putting in readme to use it will solve all issues 😂

**Comment by Amanse** [comment]
it is giving black screen on all browsers doe sadly😭

**Comment by developeranaz** [comment]
wait some more second

**Comment by Amanse** [comment]
yes, sorry, my bad😅 my impatience got to me

**Comment by developeranaz** [comment]
use brave / firefox in android 
wait for some more minutes

**Comment by Amanse** [comment]
it's working! will closing the tab kill the process?

**Comment by developeranaz** [comment]
`don't close that tab close the whole browser.`
sounds weard but the about statement is true.
i had experienced that.

**Comment by Amanse** [comment]
ohhh, wow, so it kills the process when leaving message is sent to the site, very nice, thanks! it's amazing

**Comment by developeranaz** [comment]
👍
